#!usr/bin/python

def main():
    full_name = get_full_name()
    print()
    
    password = get_password()
    print()
    
    first_name = get_first_name(full_name)
    print("Hi " + first_name + ", thanks for creating an account.")
    
def get_full_name():
    while True:                                                                             # starts a while loop to loop until condition is met for return parameter
        name = input("Enter full name:       ").strip()                                     # .strip() strips any accidental white space 
        if " " in name:                                                                     # checks for a space in the name that separates first and last name 
            return name
        else:
            print("You must enter your full name.")    
            
def get_password():
    while True:                                                                             # starts a while loop to loop until condition is met for return parameter
        password = input("Enter password:       ").strip()                                  # .strip() strips any accidental white space 
        digit = False                                                                       # Initilize variable digit and sets it to false                                                     
        cap_letter = False                                                                  # Initilize variable digit and sets it to false 
        for char in password:                                                               # Starts for loop to parse through characters to check for a digit and capital letter
            if char.isdigit():                                                              # Checks if there is a digit in the password and sets boolean to true
                digit = True
            elif char.isupper():                                                            # Checks if there is an upper case letter and sets boolean to true
                cap_letter = True
        if digit == False or cap_letter == False or len(password) < 8:                      # Conditions that must be met against the password -> print message with requirements
            print("Password must be 8 characters or more \n" +
                  "with at least one digit and one uppercase letter.")
        else:
            return password
        
def get_first_name(full_name):                                                              
    index1 = full_name.find(" ")                                                            # Finds the white space in first name
    first_name = full_name[:index1]                                                         # Sets the first part of the index, first name, to the first name variable
    return first_name

if __name__ == "__main__":
    main()
