#!usr/bin/python3

from datetime import datetime
import locale

def get_arrival_date():
    while True:                                                                             #Begin while loop to check for input
        date_str = input("Enter arrival date (YYYY-MM-DD): ")                               #Date_str is set to the input of user input
        try:                                                                                #Begin try statement
            arrival_date = datetime.strptime(date_str, "%Y-%m-%d")                          #Set arrival_date to a formatted value
        except ValueError:                                                                  #Except ValueError
            print("Invalid date format. Try again.")                                        
            continue
        
        now = datetime.now()                                                                #Set variable of now to current time
        today = datetime(now.year, now.month, now.day)                                      #Set today to value of current year, month, day
        if arrival_date < today:                                                            
            print("Arrival date must be today or later. Try again.")
            continue
        else:
            return arrival_date
        
def get_departure_date(arrival_date):
    while True:
        date_str = input("Enter departure date (YYYY-MM-DD): ")
        try:                                                                                #Begins try statement for checking user input correct format
            departure_date = datetime.strptime(date_str, "%Y-%m-%d")
        except ValueError:                                                                  #Throws error if format is invalid
            print("Invalid date format. Try again")
            continue
        
        if departure_date <= arrival_date:                                                  #If statement to do a sanity check that departure date is not before arrival date
            print("Departure date must be after arrival date. Try again")
            continue
        else:
            return departure_date
       
def main():
    print("The Hotel Reservation Program\n")
    while True:                                                                             #Begin loop to check for user input
        
        arrival_date = get_arrival_date()                                                   #Sets arrival_date to the return value of get_arrival_date
        departure_date = get_departure_date(arrival_date)                                   #Sets departure date to the return value of get_departure_date with arrival_date as a parameter 
        print()
        
        rate = 85.0 
        rate_message = ""                                                                   #Initialize rate_message 
        if arrival_date.month == 8:                                                         #If statement where if the month is August, set the rate to 105
            rate = 105.00
            rate_message = "(High season)"
        total_nights = (departure_date - arrival_date).days                                 #Sets total_nights to delta of departure from arrival in days
        total_cost = rate * total_nights                                                    #Calculates the total cost by multiplying rate by total_nights
        
        date_format = "%B %d, %Y"
        locale.setlocale(locale.LC_ALL, '')                                                 #Sets local so currency is displayed depending on where the user is
        print("Arrival Date:  ", arrival_date.strftime(date_format))
        print("Departure Date:", departure_date.strftime(date_format))
        print("Nightly rate:  ", locale.currency(rate), rate_message)
        print("Total nights:  ", total_nights)
        print("Total price:   ", locale.currency(total_cost))
        print()
        
        result = input("Continue? (y/n): ")
        print()
        if result.lower() != "y":
            print("Bye!")
            break
        
if __name__ == "__main__":
    main()
