#! usr/bin/env python3

import random

def take_turn(turn, total_score, game_over):

    print ("TURN", turn)
    score_this_turn = 0
    turn_over = False
    while not turn_over:
        choice = input("Roll or hold? (r/h): ")
        if choice == "r":
            turn, total_score, score_this_turn, turn_over = roll_die(turn, total_score, score_this_turn)
        elif choice == "h":
            turn, total_score, score_this_turn, turn_over = hold_turn(turn, total_score, score_this_turn)
        else:
            print("Invalid choice.  Try again.")
    return turn, total_score, game_over

def roll_die(turn, total_score, score_this_turn):

    die = random.randint(1, 6)
    print("Die:", die)
    if die == 1:
        score_this_turn = 0
        turn += 1
        print("Turn over.  No score.\n")
        turn_over = True
    else:
        score_this_turn += die
        turn_over = False
    return turn, total_score, score_this_turn, turn_over

def hold_turn(turn, total_score, score_this_turn):

    print("Score for turn:", score_this_turn)
    total_score += score_this_turn
    print("Total score:", total_score, "\n")
    turn_over = True
    game_over = False
    if total_score >= 20:
        print("You finished in", turn, "turns!")
        game_over = True
        return turn, total_score, turn_over, game_over
    turn += 1
    return turn, total_score, turn_over, game_over

def main():

    display_rules()
    play_game()

def display_rules():

    print("Let's play PIG!")
    print()
    print("See how many turns it takes you to get to 20.\n"
          "Turn ends when you hold or roll a 1.\n"
          "If you roll a 1, you lose all points for the turn.\n"
          "If you hold, you save all points for the turn.\n")

def play_game():

    turn = 1
    total_score = 0
    game_over = False
    while not game_over:
        turn, total_score, game_over = take_turn(turn, total_score, game_over)
    print()
    print("Game over!")

if __name__ == "__main__":
    main()
