#!usr/bin/env python3

def get_scores(scores):

    print("The Test Scores program")
    print("Enter 'x' to exit")
    print()

    while True:
        new_score = input("Enter test score: ")
        if new_score == 'x':
            break
        elif int(new_score) > 100 or int(new_score) < 0:
            print("Enter a valid score.")
        else:
            scores.append(int(new_score))
      
            
def process_scores(scores):

    total = 0
    
    for score in scores:
        total += score

    #processing algorithms

    avg = round((total / len(scores)))
    median_index = len(scores) // 2
    median = scores[median_index]

    #output
    print("Total :\t\t " + str(total))
    print("Number of scores: " + str(len(scores)))
    print("Average score:\t " + str(avg))
    print("Low score:\t " + str(min(scores)))
    print("High score:\t " + str(max(scores)))
    print("Median Score:\t " + str(median))


def main():

    #initialize variables/lists/tuples
    scores = []
    
    get_scores(scores)
    process_scores(scores)


if __name__ == "__main__":
    main()
